// SiliconForge — UPF 2.1 (IEEE 1801) Power Intent Parser
#include "frontend/upf_parser.hpp"
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <cctype>
#include <cmath>

namespace sf {

// ════════════════════════════════════════════════════════════════════════
//  UpfDesign helpers
// ════════════════════════════════════════════════════════════════════════

const PowerDomain* UpfDesign::find_domain(const std::string& name) const {
    auto it = domains.find(name);
    return it != domains.end() ? &it->second : nullptr;
}

const SupplyNet* UpfDesign::find_supply(const std::string& name) const {
    auto it = supply_nets.find(name);
    return it != supply_nets.end() ? &it->second : nullptr;
}

std::vector<std::string> UpfDesign::get_domain_hierarchy(const std::string& domain) const {
    std::vector<std::string> path;
    std::string cur = domain;
    std::unordered_set<std::string> visited;
    while (!cur.empty() && visited.find(cur) == visited.end()) {
        visited.insert(cur);
        path.push_back(cur);
        auto it = domains.find(cur);
        if (it == domains.end()) break;
        cur = it->second.parent_domain;
    }
    std::reverse(path.begin(), path.end());
    return path;
}

bool UpfDesign::validate() const {
    // We cast away const to reuse the mutable errors/warnings vectors.
    // A proper design would separate validation results; here we keep the
    // API surface clean.
    auto& self = const_cast<UpfDesign&>(*this);
    self.errors.clear();
    self.warnings.clear();

    // 1. Every domain must have primary power and ground
    for (auto& [name, dom] : domains) {
        if (dom.primary_power_net.empty())
            self.errors.push_back("Domain '" + name + "' has no primary power net");
        if (dom.primary_ground_net.empty())
            self.errors.push_back("Domain '" + name + "' has no primary ground net");
    }

    // 2. Isolation strategies must reference valid domains
    for (auto& iso : isolations) {
        if (domains.find(iso.domain) == domains.end())
            self.errors.push_back("Isolation '" + iso.name +
                                  "' references unknown domain '" + iso.domain + "'");
    }

    // 3. Level shifters must reference valid domains
    for (auto& ls : level_shifters) {
        if (domains.find(ls.domain) == domains.end())
            self.errors.push_back("Level shifter '" + ls.name +
                                  "' references unknown domain '" + ls.domain + "'");
    }

    // 4. Retention strategies must reference valid domains
    for (auto& ret : retentions) {
        if (domains.find(ret.domain) == domains.end())
            self.errors.push_back("Retention '" + ret.name +
                                  "' references unknown domain '" + ret.domain + "'");
    }

    // 5. PST supply names should exist
    for (auto& pst : state_tables) {
        for (auto& sn : pst.supply_names) {
            if (supply_nets.find(sn) == supply_nets.end())
                self.warnings.push_back("PST '" + pst.name +
                                        "' references unknown supply '" + sn + "'");
        }
    }

    // 6. Domains that can be powered off should have retention
    std::unordered_set<std::string> domains_with_off;
    for (auto& pst : state_tables) {
        for (auto& st : pst.states) {
            for (auto& [sn, v] : st.supply_voltages) {
                if (v < 0) { // OFF
                    // Find which domain owns this supply
                    for (auto& [dname, dom] : domains) {
                        if (dom.primary_power_net == sn)
                            domains_with_off.insert(dname);
                    }
                }
            }
        }
    }
    std::unordered_set<std::string> domains_with_retention;
    for (auto& ret : retentions)
        domains_with_retention.insert(ret.domain);
    for (auto& d : domains_with_off) {
        if (domains_with_retention.find(d) == domains_with_retention.end())
            self.warnings.push_back("Domain '" + d +
                                    "' can be powered off but has no retention strategy");
    }

    return self.errors.empty();
}

// ── to_upf() — export back to UPF text ─────────────────────────────────

static std::string brace_list(const std::vector<std::string>& v) {
    if (v.empty()) return "{}";
    if (v.size() == 1) return v[0];
    std::string s = "{";
    for (size_t i = 0; i < v.size(); ++i) {
        if (i) s += ' ';
        s += v[i];
    }
    s += '}';
    return s;
}

std::string UpfDesign::to_upf() const {
    std::ostringstream o;
    o << "# UPF " << version << " — generated by SiliconForge\n\n";

    // Domains
    for (auto& [name, dom] : domains) {
        o << "create_power_domain " << name;
        if (dom.is_top) o << " -include_scope";
        if (!dom.elements.empty()) o << " -elements " << brace_list(dom.elements);
        o << '\n';
    }
    o << '\n';

    // Supply nets
    for (auto& [name, sn] : supply_nets) {
        o << "create_supply_net " << name;
        // find owning domain
        for (auto& [dname, dom] : domains) {
            for (auto& s : dom.supply_nets) {
                if (s == name) { o << " -domain " << dname; goto done_sn; }
            }
        }
        done_sn:
        if (sn.is_resolved) o << " -resolve parallel";
        o << '\n';
    }
    o << '\n';

    // Supply ports
    for (auto& [name, sp] : supply_ports) {
        o << "create_supply_port " << name
          << " -domain " << sp.domain
          << " -direction " << (sp.direction == SupplyPort::IN ? "in" : "out")
          << '\n';
    }
    o << '\n';

    // Connect supply nets
    for (auto& [name, sn] : supply_nets) {
        if (!sn.connected_supply_port.empty())
            o << "connect_supply_net " << name
              << " -ports {" << sn.connected_supply_port << "}\n";
    }
    o << '\n';

    // Domain supply net assignments
    for (auto& [name, dom] : domains) {
        if (!dom.primary_power_net.empty() || !dom.primary_ground_net.empty()) {
            o << "set_domain_supply_net " << name;
            if (!dom.primary_power_net.empty())
                o << " -primary_power_net " << dom.primary_power_net;
            if (!dom.primary_ground_net.empty())
                o << " -primary_ground_net " << dom.primary_ground_net;
            o << '\n';
        }
    }
    o << '\n';

    // Isolation
    for (auto& iso : isolations) {
        o << "set_isolation " << iso.name << " -domain " << iso.domain;
        if (!iso.isolation_power_net.empty())
            o << " \\\n    -isolation_power_net " << iso.isolation_power_net;
        if (!iso.isolation_ground_net.empty())
            o << " \\\n    -isolation_ground_net " << iso.isolation_ground_net;
        o << " \\\n    -clamp_value " << static_cast<int>(iso.type);
        if (!iso.applies_to.empty())
            o << " \\\n    -applies_to " << iso.applies_to;
        if (!iso.isolation_signal.empty())
            o << " \\\n    -isolation_signal " << iso.isolation_signal;
        o << " \\\n    -sense " << (iso.sense == IsolationStrategy::HIGH ? "high" : "low");
        if (!iso.location.empty())
            o << " \\\n    -location " << iso.location;
        o << '\n';
    }
    o << '\n';

    // Level shifters
    for (auto& ls : level_shifters) {
        o << "set_level_shifter " << ls.name << " -domain " << ls.domain;
        if (!ls.applies_to.empty()) o << " \\\n    -applies_to " << ls.applies_to;
        if (!ls.rule.empty()) o << " \\\n    -rule " << ls.rule;
        if (!ls.location.empty()) o << " \\\n    -location " << ls.location;
        o << '\n';
    }
    o << '\n';

    // Retention
    for (auto& ret : retentions) {
        o << "set_retention " << ret.name << " -domain " << ret.domain;
        if (!ret.retention_power_net.empty())
            o << " \\\n    -retention_power_net " << ret.retention_power_net;
        if (!ret.save_signal.empty())
            o << " \\\n    -save_signal {" << ret.save_signal << "}";
        if (!ret.restore_signal.empty())
            o << " \\\n    -restore_signal {" << ret.restore_signal << "}";
        o << '\n';
    }
    o << '\n';

    // Power states
    for (auto& pst : state_tables) {
        o << "create_pst " << pst.name
          << " -supplies " << brace_list(pst.supply_names) << '\n';
        for (auto& st : pst.states) {
            o << "add_pst_state " << pst.name << '.' << st.name
              << " -pst " << pst.name << " -state {";
            for (size_t i = 0; i < pst.supply_names.size(); ++i) {
                if (i) o << ' ';
                auto it = st.supply_voltages.find(pst.supply_names[i]);
                if (it != st.supply_voltages.end() && it->second < 0)
                    o << "OFF";
                else
                    o << "ON";
            }
            o << "}\n";
        }
    }

    return o.str();
}

// ── report() — human-readable summary ───────────────────────────────────

std::string UpfDesign::report() const {
    std::ostringstream o;
    o << "=======================================\n"
      << " SiliconForge UPF Power Intent Report\n"
      << "=======================================\n";

    // Domains
    o << "Domains: " << domains.size() << " (";
    { bool first = true;
      for (auto& [n, _] : domains) { if (!first) o << ", "; o << n; first = false; }
    }
    o << ")\n";

    // Supplies
    o << "Supplies: " << supply_nets.size() << " (";
    { bool first = true;
      for (auto& [n, s] : supply_nets) {
          if (!first) o << ", ";
          o << n << '=' << s.voltage << 'V';
          first = false;
      }
    }
    o << ")\n";

    // Isolation
    o << "Isolation: " << isolations.size() << " strategies (";
    { bool first = true;
      for (auto& iso : isolations) { if (!first) o << ", "; o << iso.name; first = false; }
    }
    o << ")\n";

    // Level shifters
    o << "Level Shifters: " << level_shifters.size() << " (";
    { bool first = true;
      for (auto& ls : level_shifters) { if (!first) o << ", "; o << ls.name; first = false; }
    }
    o << ")\n";

    // Retention
    o << "Retention: " << retentions.size() << " (";
    { bool first = true;
      for (auto& r : retentions) { if (!first) o << ", "; o << r.name; first = false; }
    }
    o << ")\n";

    // Power states (count all states across tables)
    size_t total_states = 0;
    for (auto& pst : state_tables) total_states += pst.states.size();
    o << "Power States: " << total_states << " (";
    { bool first = true;
      for (auto& pst : state_tables)
          for (auto& st : pst.states) {
              if (!first) o << ", "; o << st.name; first = false;
          }
    }
    o << ")\n";

    // Validation
    auto& self = const_cast<UpfDesign&>(*this);
    bool ok = self.validate();
    o << "Validation: " << (ok ? "PASS" : "FAIL")
      << " (" << errors.size() << " errors, " << warnings.size() << " warnings)\n";

    return o.str();
}

// ════════════════════════════════════════════════════════════════════════
//  UpfParser — TCL-like tokeniser
// ════════════════════════════════════════════════════════════════════════

void UpfParser::error(UpfDesign& upf, int line, const std::string& msg) {
    upf.errors.push_back("line " + std::to_string(line) + ": " + msg);
}

void UpfParser::warn(UpfDesign& upf, int line, const std::string& msg) {
    upf.warnings.push_back("line " + std::to_string(line) + ": " + msg);
}

std::vector<UpfParser::Command> UpfParser::split_into_commands(const std::string& content) {
    std::vector<Command> cmds;
    std::istringstream stream(content);
    std::string logical_line;
    int line_num = 0;
    int cmd_start = 0;

    std::string raw;
    while (std::getline(stream, raw)) {
        ++line_num;
        // Strip trailing \r
        if (!raw.empty() && raw.back() == '\r') raw.pop_back();
        // Strip inline comments (not inside braces/quotes)
        {
            bool in_brace = false, in_quote = false;
            for (size_t i = 0; i < raw.size(); ++i) {
                if (raw[i] == '{') in_brace = true;
                else if (raw[i] == '}') in_brace = false;
                else if (raw[i] == '"') in_quote = !in_quote;
                else if (raw[i] == '#' && !in_brace && !in_quote) {
                    raw = raw.substr(0, i);
                    break;
                }
            }
        }
        // Handle backslash continuation
        if (!raw.empty() && raw.back() == '\\') {
            if (logical_line.empty()) cmd_start = line_num;
            logical_line += raw.substr(0, raw.size() - 1) + ' ';
            continue;
        }
        if (logical_line.empty()) cmd_start = line_num;
        logical_line += raw;

        // Trim
        auto start = logical_line.find_first_not_of(" \t");
        if (start != std::string::npos) {
            auto end = logical_line.find_last_not_of(" \t");
            std::string trimmed = logical_line.substr(start, end - start + 1);
            if (!trimmed.empty()) {
                Command cmd;
                cmd.args = tokenize(trimmed);
                cmd.line_number = cmd_start;
                if (!cmd.args.empty()) cmds.push_back(std::move(cmd));
            }
        }
        logical_line.clear();
    }
    // Flush any remaining continuation
    if (!logical_line.empty()) {
        auto start = logical_line.find_first_not_of(" \t");
        if (start != std::string::npos) {
            auto end = logical_line.find_last_not_of(" \t");
            Command cmd;
            cmd.args = tokenize(logical_line.substr(start, end - start + 1));
            cmd.line_number = cmd_start;
            if (!cmd.args.empty()) cmds.push_back(std::move(cmd));
        }
    }
    return cmds;
}

std::vector<std::string> UpfParser::tokenize(const std::string& line) {
    std::vector<std::string> tokens;
    std::string cur;
    int brace_depth = 0;
    bool in_quote = false;

    for (size_t i = 0; i < line.size(); ++i) {
        char c = line[i];

        if (in_quote) {
            if (c == '"') {
                in_quote = false;
                if (!cur.empty()) { tokens.push_back(cur); cur.clear(); }
            } else {
                cur += c;
            }
            continue;
        }

        if (brace_depth > 0) {
            if (c == '{') {
                ++brace_depth;
                cur += c;
            } else if (c == '}') {
                --brace_depth;
                if (brace_depth == 0) {
                    // Emit the brace-grouped content as a single token
                    tokens.push_back(cur);
                    cur.clear();
                } else {
                    cur += c;
                }
            } else {
                cur += c;
            }
            continue;
        }

        if (c == '"') {
            in_quote = true;
            if (!cur.empty()) { tokens.push_back(cur); cur.clear(); }
        } else if (c == '{') {
            if (!cur.empty()) { tokens.push_back(cur); cur.clear(); }
            ++brace_depth;
        } else if (std::isspace(static_cast<unsigned char>(c))) {
            if (!cur.empty()) { tokens.push_back(cur); cur.clear(); }
        } else {
            cur += c;
        }
    }
    if (!cur.empty()) tokens.push_back(cur);
    return tokens;
}

// ── Flag extraction helpers ─────────────────────────────────────────────

std::string UpfParser::get_flag(const std::vector<std::string>& args,
                                const std::string& flag,
                                const std::string& default_val) {
    for (size_t i = 0; i + 1 < args.size(); ++i)
        if (args[i] == flag) return args[i + 1];
    return default_val;
}

std::vector<std::string> UpfParser::get_flag_list(const std::vector<std::string>& args,
                                                  const std::string& flag) {
    std::string raw = get_flag(args, flag, "");
    if (raw.empty()) return {};
    // The value may be a single token or a space-separated brace group
    std::vector<std::string> out;
    std::istringstream ss(raw);
    std::string tok;
    while (ss >> tok) out.push_back(tok);
    return out;
}

bool UpfParser::has_flag(const std::vector<std::string>& args,
                         const std::string& flag) {
    for (auto& a : args)
        if (a == flag) return true;
    return false;
}

// ════════════════════════════════════════════════════════════════════════
//  Top-level parse entry points
// ════════════════════════════════════════════════════════════════════════

UpfDesign UpfParser::parse_file(const std::string& filename) {
    std::ifstream f(filename);
    if (!f.is_open()) {
        UpfDesign upf;
        upf.errors.push_back("Cannot open file: " + filename);
        return upf;
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    return parse_string(ss.str());
}

UpfDesign UpfParser::parse_string(const std::string& content) {
    UpfDesign upf;
    auto cmds = split_into_commands(content);

    for (auto& cmd : cmds) {
        if (cmd.args.empty() || cmd.args[0][0] == '#') continue;

        const std::string& name = cmd.args[0];
        if      (name == "create_power_domain")  parse_create_power_domain(cmd.args, upf, cmd.line_number);
        else if (name == "create_supply_net")     parse_create_supply_net(cmd.args, upf, cmd.line_number);
        else if (name == "create_supply_port")    parse_create_supply_port(cmd.args, upf, cmd.line_number);
        else if (name == "connect_supply_net")    parse_connect_supply_net(cmd.args, upf, cmd.line_number);
        else if (name == "set_domain_supply_net") parse_set_domain_supply_net(cmd.args, upf, cmd.line_number);
        else if (name == "set_isolation")         parse_set_isolation(cmd.args, upf, cmd.line_number);
        else if (name == "set_level_shifter")     parse_set_level_shifter(cmd.args, upf, cmd.line_number);
        else if (name == "set_retention")         parse_set_retention(cmd.args, upf, cmd.line_number);
        else if (name == "add_power_state")       parse_add_power_state(cmd.args, upf, cmd.line_number);
        else if (name == "create_pst")            parse_create_pst(cmd.args, upf, cmd.line_number);
        else if (name == "add_pst_state")         parse_add_pst_state(cmd.args, upf, cmd.line_number);
        // Skip unknown commands gracefully
    }
    return upf;
}

// ════════════════════════════════════════════════════════════════════════
//  Per-command parsers
// ════════════════════════════════════════════════════════════════════════

void UpfParser::parse_create_power_domain(const std::vector<std::string>& args,
                                          UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "create_power_domain: missing domain name"); return; }
    std::string name = args[1];
    PowerDomain dom;
    dom.name = name;
    dom.is_top = has_flag(args, "-include_scope");
    dom.elements = get_flag_list(args, "-elements");

    std::string parent = get_flag(args, "-scope");
    if (!parent.empty()) dom.parent_domain = parent;

    double v = 0;
    std::string vs = get_flag(args, "-voltage");
    if (!vs.empty()) {
        try { v = std::stod(vs); } catch (...) {}
        dom.voltage = v;
    }

    upf.domains[name] = std::move(dom);
}

void UpfParser::parse_create_supply_net(const std::vector<std::string>& args,
                                        UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "create_supply_net: missing net name"); return; }
    std::string name = args[1];
    SupplyNet sn;
    sn.name = name;
    sn.is_resolved = has_flag(args, "-resolve");

    std::string vs = get_flag(args, "-voltage");
    if (!vs.empty()) {
        try { sn.voltage = std::stod(vs); } catch (...) {}
    }

    upf.supply_nets[name] = std::move(sn);

    // Associate with domain
    std::string domain = get_flag(args, "-domain");
    if (!domain.empty()) {
        auto it = upf.domains.find(domain);
        if (it != upf.domains.end())
            it->second.supply_nets.push_back(name);
        else
            warn(upf, line, "create_supply_net: domain '" + domain + "' not yet defined");
    }
}

void UpfParser::parse_create_supply_port(const std::vector<std::string>& args,
                                         UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "create_supply_port: missing port name"); return; }
    SupplyPort sp;
    sp.name = args[1];
    sp.domain = get_flag(args, "-domain");
    std::string dir = get_flag(args, "-direction", "in");
    sp.direction = (dir == "out") ? SupplyPort::OUT : SupplyPort::IN;
    upf.supply_ports[sp.name] = std::move(sp);
}

void UpfParser::parse_connect_supply_net(const std::vector<std::string>& args,
                                         UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "connect_supply_net: missing net name"); return; }
    std::string net_name = args[1];
    auto ports = get_flag_list(args, "-ports");

    auto it = upf.supply_nets.find(net_name);
    if (it == upf.supply_nets.end()) {
        warn(upf, line, "connect_supply_net: supply net '" + net_name + "' not defined");
        return;
    }
    if (!ports.empty())
        it->second.connected_supply_port = ports[0];
}

void UpfParser::parse_set_domain_supply_net(const std::vector<std::string>& args,
                                            UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "set_domain_supply_net: missing domain name"); return; }
    std::string domain = args[1];
    auto it = upf.domains.find(domain);
    if (it == upf.domains.end()) {
        error(upf, line, "set_domain_supply_net: unknown domain '" + domain + "'");
        return;
    }
    std::string ppn = get_flag(args, "-primary_power_net");
    std::string pgn = get_flag(args, "-primary_ground_net");
    if (!ppn.empty()) it->second.primary_power_net = ppn;
    if (!pgn.empty()) it->second.primary_ground_net = pgn;

    // Propagate voltage from supply net
    if (!ppn.empty()) {
        auto sn = upf.supply_nets.find(ppn);
        if (sn != upf.supply_nets.end() && sn->second.voltage > 0)
            it->second.voltage = sn->second.voltage;
    }
}

void UpfParser::parse_set_isolation(const std::vector<std::string>& args,
                                    UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "set_isolation: missing strategy name"); return; }
    IsolationStrategy iso;
    iso.name = args[1];
    iso.domain = get_flag(args, "-domain");
    iso.isolation_power_net = get_flag(args, "-isolation_power_net");
    iso.isolation_ground_net = get_flag(args, "-isolation_ground_net");
    iso.applies_to = get_flag(args, "-applies_to", "outputs");
    iso.isolation_signal = get_flag(args, "-isolation_signal");
    iso.location = get_flag(args, "-location", "parent");

    // Clamp value
    std::string cv = get_flag(args, "-clamp_value", "0");
    if      (cv == "0")     iso.type = IsolationStrategy::CLAMP_0;
    else if (cv == "1")     iso.type = IsolationStrategy::CLAMP_1;
    else if (cv == "latch") iso.type = IsolationStrategy::LATCH;

    // Sense
    std::string sense = get_flag(args, "-sense", "high");
    iso.sense = (sense == "low") ? IsolationStrategy::LOW : IsolationStrategy::HIGH;

    if (iso.domain.empty())
        warn(upf, line, "set_isolation '" + iso.name + "': no -domain specified");

    upf.isolations.push_back(std::move(iso));
}

void UpfParser::parse_set_level_shifter(const std::vector<std::string>& args,
                                        UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "set_level_shifter: missing name"); return; }
    LevelShifter ls;
    ls.name = args[1];
    ls.domain = get_flag(args, "-domain");
    ls.applies_to = get_flag(args, "-applies_to", "both");
    ls.rule = get_flag(args, "-rule", "both");
    ls.location = get_flag(args, "-location", "self");
    ls.threshold = get_flag(args, "-threshold");

    std::string iv = get_flag(args, "-input_voltage");
    std::string ov = get_flag(args, "-output_voltage");
    if (!iv.empty()) { try { ls.input_voltage = std::stod(iv); } catch (...) {} }
    if (!ov.empty()) { try { ls.output_voltage = std::stod(ov); } catch (...) {} }

    if (ls.domain.empty())
        warn(upf, line, "set_level_shifter '" + ls.name + "': no -domain specified");

    upf.level_shifters.push_back(std::move(ls));
}

void UpfParser::parse_set_retention(const std::vector<std::string>& args,
                                    UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "set_retention: missing name"); return; }
    RetentionStrategy ret;
    ret.name = args[1];
    ret.domain = get_flag(args, "-domain");
    ret.retention_power_net = get_flag(args, "-retention_power_net");
    ret.retention_ground_net = get_flag(args, "-retention_ground_net");

    // Save/restore signals may be brace-grouped
    auto save_list = get_flag_list(args, "-save_signal");
    if (!save_list.empty()) ret.save_signal = save_list[0];
    auto restore_list = get_flag_list(args, "-restore_signal");
    if (!restore_list.empty()) ret.restore_signal = restore_list[0];

    ret.elements = get_flag_list(args, "-elements");

    std::string sc = get_flag(args, "-save_condition", "edge");
    ret.save_condition = (sc == "level") ? RetentionStrategy::LEVEL : RetentionStrategy::EDGE;

    if (ret.domain.empty())
        warn(upf, line, "set_retention '" + ret.name + "': no -domain specified");

    upf.retentions.push_back(std::move(ret));
}

void UpfParser::parse_add_power_state(const std::vector<std::string>& args,
                                      UpfDesign& upf, int line) {
    // Syntax: add_power_state DOMAIN.state -supply {NET voltage} [-supply ...] -simstate STATE
    if (args.size() < 2) { error(upf, line, "add_power_state: missing state name"); return; }

    std::string qualified = args[1]; // e.g. "PD_TOP.active"
    std::string domain_name, state_name;
    auto dot = qualified.find('.');
    if (dot != std::string::npos) {
        domain_name = qualified.substr(0, dot);
        state_name = qualified.substr(dot + 1);
    } else {
        state_name = qualified;
    }

    PowerState ps;
    ps.name = state_name;
    ps.simstate = get_flag(args, "-simstate", "NORMAL");

    // Collect all -supply flags (there may be multiple)
    for (size_t i = 0; i + 1 < args.size(); ++i) {
        if (args[i] == "-supply") {
            // Value is brace-grouped: "NET voltage" or "NET OFF"
            std::string raw = args[i + 1];
            std::istringstream ss(raw);
            std::string sname, sval;
            if (ss >> sname >> sval) {
                if (sval == "OFF" || sval == "off")
                    ps.supply_voltages[sname] = -1.0;
                else {
                    try { ps.supply_voltages[sname] = std::stod(sval); } catch (...) {
                        ps.supply_voltages[sname] = 0.0;
                    }
                }
                // Also update the supply net's voltage if it's a resolved value
                if (ps.supply_voltages[sname] > 0) {
                    auto it = upf.supply_nets.find(sname);
                    if (it != upf.supply_nets.end() && it->second.voltage == 0.0)
                        it->second.voltage = ps.supply_voltages[sname];
                }
            }
        }
    }

    // Find or create a state table for this domain
    if (!domain_name.empty()) {
        // Look for an existing implicit state table for this domain
        bool found = false;
        for (auto& pst : upf.state_tables) {
            if (pst.name == domain_name + "_pst") {
                pst.states.push_back(std::move(ps));
                found = true;
                break;
            }
        }
        if (!found) {
            PowerStateTable pst;
            pst.name = domain_name + "_pst";
            // Collect supply names from the power state
            for (auto& [sn, _] : ps.supply_voltages)
                pst.supply_names.push_back(sn);
            pst.states.push_back(std::move(ps));
            upf.state_tables.push_back(std::move(pst));
        }
    }
}

void UpfParser::parse_create_pst(const std::vector<std::string>& args,
                                 UpfDesign& upf, int line) {
    if (args.size() < 2) { error(upf, line, "create_pst: missing PST name"); return; }
    PowerStateTable pst;
    pst.name = args[1];
    pst.supply_names = get_flag_list(args, "-supplies");
    upf.state_tables.push_back(std::move(pst));
}

void UpfParser::parse_add_pst_state(const std::vector<std::string>& args,
                                    UpfDesign& upf, int line) {
    // Syntax: add_pst_state pst1.s1 -pst pst1 -state {ON OFF}
    if (args.size() < 2) { error(upf, line, "add_pst_state: missing state name"); return; }

    std::string qualified = args[1];
    std::string state_name;
    auto dot = qualified.find('.');
    state_name = (dot != std::string::npos) ? qualified.substr(dot + 1) : qualified;

    std::string pst_name = get_flag(args, "-pst");
    auto state_vals = get_flag_list(args, "-state");

    // Find the PST
    PowerStateTable* target = nullptr;
    for (auto& pst : upf.state_tables) {
        if (pst.name == pst_name) { target = &pst; break; }
    }
    if (!target) {
        error(upf, line, "add_pst_state: PST '" + pst_name + "' not found");
        return;
    }

    PowerState ps;
    ps.name = state_name;
    for (size_t i = 0; i < state_vals.size() && i < target->supply_names.size(); ++i) {
        if (state_vals[i] == "ON" || state_vals[i] == "on")
            ps.supply_voltages[target->supply_names[i]] = 1.0; // nominal
        else if (state_vals[i] == "OFF" || state_vals[i] == "off")
            ps.supply_voltages[target->supply_names[i]] = -1.0;
        else {
            try { ps.supply_voltages[target->supply_names[i]] = std::stod(state_vals[i]); }
            catch (...) { ps.supply_voltages[target->supply_names[i]] = 0.0; }
        }
    }
    target->states.push_back(std::move(ps));
}

// ════════════════════════════════════════════════════════════════════════
//  UpfChecker — DRC for power intent
// ════════════════════════════════════════════════════════════════════════

std::vector<std::string> UpfChecker::check(const UpfDesign& upf, const Netlist& nl) {
    std::vector<std::string> issues;
    check_domain_supplies(upf, issues);
    check_isolation_refs(upf, issues);
    check_level_shifters(upf, issues);
    check_retention_coverage(upf, issues);
    check_supply_consistency(upf, issues);
    check_pst_validity(upf, issues);
    check_netlist_coverage(upf, nl, issues);
    return issues;
}

void UpfChecker::check_domain_supplies(const UpfDesign& upf,
                                       std::vector<std::string>& issues) {
    for (auto& [name, dom] : upf.domains) {
        if (dom.primary_power_net.empty())
            issues.push_back("[ERROR] Domain '" + name + "' has no primary power net");
        else if (upf.supply_nets.find(dom.primary_power_net) == upf.supply_nets.end())
            issues.push_back("[ERROR] Domain '" + name + "' power net '" +
                             dom.primary_power_net + "' is not defined");

        if (dom.primary_ground_net.empty())
            issues.push_back("[ERROR] Domain '" + name + "' has no primary ground net");
        else if (upf.supply_nets.find(dom.primary_ground_net) == upf.supply_nets.end())
            issues.push_back("[ERROR] Domain '" + name + "' ground net '" +
                             dom.primary_ground_net + "' is not defined");
    }
}

void UpfChecker::check_isolation_refs(const UpfDesign& upf,
                                      std::vector<std::string>& issues) {
    for (auto& iso : upf.isolations) {
        if (upf.domains.find(iso.domain) == upf.domains.end())
            issues.push_back("[ERROR] Isolation '" + iso.name +
                             "' references unknown domain '" + iso.domain + "'");
        if (!iso.isolation_power_net.empty() &&
            upf.supply_nets.find(iso.isolation_power_net) == upf.supply_nets.end())
            issues.push_back("[WARN] Isolation '" + iso.name +
                             "' power net '" + iso.isolation_power_net + "' is not defined");
        if (iso.isolation_signal.empty())
            issues.push_back("[WARN] Isolation '" + iso.name + "' has no isolation signal");
    }
}

void UpfChecker::check_level_shifters(const UpfDesign& upf,
                                      std::vector<std::string>& issues) {
    // Build set of domains that have level shifters
    std::unordered_set<std::string> domains_with_ls;
    for (auto& ls : upf.level_shifters) {
        if (upf.domains.find(ls.domain) == upf.domains.end())
            issues.push_back("[ERROR] Level shifter '" + ls.name +
                             "' references unknown domain '" + ls.domain + "'");
        domains_with_ls.insert(ls.domain);
    }

    // Check that domains at different voltages have level shifters
    for (auto& [n1, d1] : upf.domains) {
        for (auto& [n2, d2] : upf.domains) {
            if (n1 >= n2) continue; // avoid duplicates
            if (std::abs(d1.voltage - d2.voltage) > 0.01) {
                bool has_ls = domains_with_ls.count(n1) || domains_with_ls.count(n2);
                if (!has_ls)
                    issues.push_back("[WARN] Domains '" + n1 + "' (" +
                                     std::to_string(d1.voltage) + "V) and '" + n2 + "' (" +
                                     std::to_string(d2.voltage) + "V) have different voltages"
                                     " but no level shifter is defined");
            }
        }
    }
}

void UpfChecker::check_retention_coverage(const UpfDesign& upf,
                                          std::vector<std::string>& issues) {
    // Find domains that can be powered off
    std::unordered_set<std::string> can_power_off;
    for (auto& pst : upf.state_tables) {
        for (auto& st : pst.states) {
            for (auto& [sn, v] : st.supply_voltages) {
                if (v < 0) {
                    for (auto& [dname, dom] : upf.domains)
                        if (dom.primary_power_net == sn)
                            can_power_off.insert(dname);
                }
            }
        }
    }

    std::unordered_set<std::string> has_retention;
    for (auto& ret : upf.retentions) has_retention.insert(ret.domain);

    for (auto& d : can_power_off) {
        if (has_retention.find(d) == has_retention.end())
            issues.push_back("[WARN] Domain '" + d +
                             "' can be powered off but has no retention strategy");
    }
}

void UpfChecker::check_supply_consistency(const UpfDesign& upf,
                                          std::vector<std::string>& issues) {
    for (auto& [name, sn] : upf.supply_nets) {
        if (sn.voltage < 0)
            issues.push_back("[WARN] Supply '" + name + "' has negative voltage");
    }
    // Check domain voltages are positive
    for (auto& [name, dom] : upf.domains) {
        if (dom.voltage < 0)
            issues.push_back("[ERROR] Domain '" + name + "' has negative voltage");
    }
}

void UpfChecker::check_pst_validity(const UpfDesign& upf,
                                    std::vector<std::string>& issues) {
    for (auto& pst : upf.state_tables) {
        if (pst.supply_names.empty())
            issues.push_back("[WARN] PST '" + pst.name + "' has no supply columns defined");

        for (auto& sn : pst.supply_names) {
            if (upf.supply_nets.find(sn) == upf.supply_nets.end())
                issues.push_back("[WARN] PST '" + pst.name +
                                 "' references unknown supply '" + sn + "'");
        }

        if (pst.states.empty())
            issues.push_back("[WARN] PST '" + pst.name + "' has no states defined");

        // Check that all states cover all supply columns
        for (auto& st : pst.states) {
            for (auto& sn : pst.supply_names) {
                if (st.supply_voltages.find(sn) == st.supply_voltages.end())
                    issues.push_back("[WARN] PST '" + pst.name + "' state '" + st.name +
                                     "' does not specify supply '" + sn + "'");
            }
        }
    }
}

void UpfChecker::check_netlist_coverage(const UpfDesign& upf, const Netlist& nl,
                                        std::vector<std::string>& issues) {
    // Build a set of gate names from the netlist for cross-referencing
    std::unordered_set<std::string> nl_instances;
    for (auto& g : nl.gates())
        if (!g.name.empty()) nl_instances.insert(g.name);

    // Check that domain elements exist in the netlist
    for (auto& [dname, dom] : upf.domains) {
        for (auto& elem : dom.elements) {
            if (nl_instances.find(elem) == nl_instances.end())
                issues.push_back("[WARN] Domain '" + dname +
                                 "' element '" + elem + "' not found in netlist");
        }
    }

    // Check that non-top domains without elements have at least a warning
    for (auto& [dname, dom] : upf.domains) {
        if (!dom.is_top && dom.elements.empty())
            issues.push_back("[INFO] Domain '" + dname +
                             "' has no explicit element list");
    }

    // Check for isolation on domain boundaries
    std::unordered_set<std::string> isolated_domains;
    for (auto& iso : upf.isolations)
        isolated_domains.insert(iso.domain);

    for (auto& [dname, dom] : upf.domains) {
        if (dom.is_top) continue;
        if (isolated_domains.find(dname) == isolated_domains.end())
            issues.push_back("[WARN] Non-top domain '" + dname +
                             "' has no isolation strategy — signals crossing boundary"
                             " may be unprotected");
    }
}

} // namespace sf
