// SiliconForge — Memory Compiler Implementation
#include "macro/memory_compiler.hpp"
#include <sstream>
#include <cmath>
#include <algorithm>

namespace sf {

void MemoryCompiler::compute_dimensions(const MemoryConfig& cfg, MemoryResult& r) {
    // Array dimensions: rows × columns
    int rows = (int)std::sqrt(cfg.words);
    int cols = cfg.words / rows;
    if (rows * cols < cfg.words) cols++;

    // Bit cell array
    double array_w = cols * cfg.bits * cfg.bit_cell_width;
    double array_h = rows * cfg.bit_cell_height;

    // Add periphery: decoders, sense amps, write drivers
    r.width_um = array_w * cfg.decoder_overhead;
    r.height_um = array_h + cfg.sense_amp_height + (array_h * cfg.periphery_ratio);
    r.area_um2 = r.width_um * r.height_um;
    r.bit_density = (cfg.words * cfg.bits) / r.area_um2;
}

void MemoryCompiler::compute_timing(const MemoryConfig& cfg, MemoryResult& r) {
    // Timing model based on word/bit count
    double depth_factor = std::log2(cfg.words) / 8.0; // normalized to 256 words
    double width_factor = cfg.bits / 32.0;

    r.timing.tAA_ns = 0.5 + 0.3 * depth_factor;
    r.timing.tCK_ns = r.timing.tAA_ns * 1.5;
    r.timing.tSetup_ns = 0.05 + 0.02 * depth_factor;
    r.timing.tHold_ns = 0.02;
    r.timing.tWC_ns = r.timing.tCK_ns;

    if (cfg.type == MemoryConfig::REGISTER_FILE) {
        r.timing.tAA_ns *= 0.6;   // RFs are faster
        r.timing.tCK_ns *= 0.6;
    }
}

void MemoryCompiler::compute_power(const MemoryConfig& cfg, MemoryResult& r) {
    double total_bits = cfg.words * cfg.bits;
    r.leakage_uw = total_bits * 0.001; // 1nW per bit
    r.read_energy_pj = total_bits * 0.0005 + cfg.bits * 0.1;
    r.write_energy_pj = r.read_energy_pj * 1.2;
}

void MemoryCompiler::generate_netlist(const MemoryConfig& cfg, MemoryResult& r) {
    auto& nl = r.netlist;
    int addr_bits = (int)std::ceil(std::log2(cfg.words));

    // Ports
    NetId clk = nl.add_net("CLK"); nl.mark_input(clk);
    NetId we = nl.add_net("WE"); nl.mark_input(we);
    NetId ce = nl.add_net("CE"); nl.mark_input(ce);

    std::vector<NetId> addr;
    for (int i = 0; i < addr_bits; ++i) {
        NetId a = nl.add_net("A[" + std::to_string(i) + "]");
        nl.mark_input(a); addr.push_back(a);
    }
    std::vector<NetId> din, dout;
    for (int i = 0; i < cfg.bits; ++i) {
        NetId d = nl.add_net("D[" + std::to_string(i) + "]"); nl.mark_input(d); din.push_back(d);
        NetId q = nl.add_net("Q[" + std::to_string(i) + "]"); nl.mark_output(q); dout.push_back(q);
    }

    // Internal: decoder, bit cells (abstracted as DFFs for functional model)
    for (int i = 0; i < cfg.bits; ++i) {
        NetId w = nl.add_net("mem_" + std::to_string(i));
        nl.add_dff(din[i], clk, w, -1, "bit_" + std::to_string(i));
        nl.add_gate(GateType::BUF, {w}, dout[i], "out_buf_" + std::to_string(i));
    }
}

void MemoryCompiler::generate_liberty(const MemoryConfig& cfg, MemoryResult& r) {
    std::ostringstream lib;
    int addr_bits = (int)std::ceil(std::log2(cfg.words));

    lib << "cell(" << cfg.name << ") {\n"
        << "  area : " << r.area_um2 << ";\n"
        << "  memory() {\n"
        << "    type : ram;\n"
        << "    address_width : " << addr_bits << ";\n"
        << "    word_width : " << cfg.bits << ";\n"
        << "  }\n"
        << "  pin(CLK) { direction : input; clock : true; }\n"
        << "  pin(CE) { direction : input; }\n"
        << "  pin(WE) { direction : input; }\n"
        << "  bus(A) { bus_type : A; direction : input; }\n"
        << "  bus(D) { bus_type : D; direction : input; }\n"
        << "  bus(Q) {\n"
        << "    bus_type : Q; direction : output;\n"
        << "    timing() {\n"
        << "      related_pin : CLK;\n"
        << "      cell_rise : " << r.timing.tAA_ns << ";\n"
        << "      cell_fall : " << r.timing.tAA_ns << ";\n"
        << "    }\n"
        << "  }\n"
        << "}\n";
    r.liberty_model = lib.str();
}

void MemoryCompiler::generate_verilog(const MemoryConfig& cfg, MemoryResult& r) {
    int addr_bits = (int)std::ceil(std::log2(cfg.words));
    std::ostringstream v;

    v << "// Generated by SiliconForge Memory Compiler\n"
      << "module " << cfg.name << " (\n"
      << "  input CLK, CE, WE,\n"
      << "  input [" << (addr_bits-1) << ":0] A,\n"
      << "  input [" << (cfg.bits-1) << ":0] D,\n"
      << "  output reg [" << (cfg.bits-1) << ":0] Q\n"
      << ");\n\n"
      << "  reg [" << (cfg.bits-1) << ":0] mem [0:" << (cfg.words-1) << "];\n\n"
      << "  always @(posedge CLK) begin\n"
      << "    if (CE) begin\n"
      << "      if (WE)\n"
      << "        mem[A] <= D;\n"
      << "      Q <= mem[A];\n"
      << "    end\n"
      << "  end\n\n"
      << "endmodule\n";
    r.verilog_model = v.str();
}

MemoryResult MemoryCompiler::compile(const MemoryConfig& cfg) {
    MemoryResult r;
    r.name = cfg.name;
    r.words = cfg.words;
    r.bits = cfg.bits;

    compute_dimensions(cfg, r);
    compute_timing(cfg, r);
    compute_power(cfg, r);
    generate_netlist(cfg, r);
    generate_liberty(cfg, r);
    generate_verilog(cfg, r);

    r.success = true;
    r.message = cfg.name + ": " + std::to_string(cfg.words) + "×" +
                std::to_string(cfg.bits) + " " +
                (cfg.type == MemoryConfig::SRAM_1P ? "SRAM" :
                 cfg.type == MemoryConfig::REGISTER_FILE ? "RF" : "ROM") +
                " — " + std::to_string((int)r.width_um) + "×" +
                std::to_string((int)r.height_um) + "um, tAA=" +
                std::to_string(r.timing.tAA_ns) + "ns";
    return r;
}

} // namespace sf
