// SiliconForge — Report Generator Implementation
#include "core/report_gen.hpp"
#include <iomanip>

namespace sf {

std::string ReportGenerator::separator(int width) {
    return std::string(width, '=') + "\n";
}

std::string ReportGenerator::header(const std::string& title, int width) {
    std::ostringstream ss;
    ss << separator(width);
    int pad = (width - (int)title.size() - 2) / 2;
    ss << std::string(std::max(0, pad), ' ') << "  " << title << "\n";
    ss << separator(width);
    return ss.str();
}

void ReportGenerator::add_timing(const StaResult& sta) {
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(3);
    ss << "  WNS (Worst Negative Slack):  " << sta.wns << " ns\n";
    ss << "  TNS (Total Negative Slack):   " << sta.tns << " ns\n";
    ss << "  Timing status:                " << (sta.wns >= 0 ? "MET" : "VIOLATED") << "\n";

    if (!sta.critical_paths.empty()) {
        ss << "  Critical paths (" << sta.critical_paths.size() << "):\n";
        int shown = std::min((int)sta.critical_paths.size(), 3);
        for (int i = 0; i < shown; ++i) {
            ss << "    [" << i << "] slack=" << sta.critical_paths[i].slack
               << "ns, " << sta.critical_paths[i].gates.size() << " stages\n";
        }
    }
    sections_.push_back({"TIMING ANALYSIS", ss.str()});
}

void ReportGenerator::add_power(const PowerResult& pwr) {
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(4);
    ss << "  Dynamic power:       " << pwr.dynamic_power_mw << " mW\n";
    ss << "  Leakage power:       " << pwr.static_power_mw << " mW\n";
    ss << "  Total power:         " << pwr.total_power_mw << " mW\n";
    if (pwr.total_power_mw > 0) {
        ss << "  Dynamic %:           "
           << (int)(pwr.dynamic_power_mw / pwr.total_power_mw * 100) << "%\n";
    }
    sections_.push_back({"POWER ANALYSIS", ss.str()});
}

void ReportGenerator::add_area(const Netlist& nl, const PhysicalDesign& pd) {
    std::ostringstream ss;
    ss << "  Gate count:          " << nl.num_gates() << "\n";
    ss << "  Net count:           " << nl.num_nets() << "\n";
    ss << "  Cell count:          " << pd.cells.size() << "\n";
    ss << "  Die area:            " << std::fixed << std::setprecision(1)
       << pd.die_area.area() << " um²\n";
    ss << "  Die dimensions:      " << (int)pd.die_area.width()
       << " × " << (int)pd.die_area.height() << " um\n";
    double util = pd.utilization() * 100;
    ss << "  Utilization:         " << (int)util << "%\n";
    sections_.push_back({"AREA SUMMARY", ss.str()});
}

void ReportGenerator::add_drc_summary(int violations, int warnings) {
    std::ostringstream ss;
    ss << "  DRC violations:      " << violations << "\n";
    ss << "  DRC warnings:        " << warnings << "\n";
    ss << "  Status:              " << (violations == 0 ? "CLEAN" : "DIRTY") << "\n";
    sections_.push_back({"DRC STATUS", ss.str()});
}

void ReportGenerator::add_custom(const std::string& title, const std::string& content) {
    sections_.push_back({title, content});
}

std::string ReportGenerator::generate() const {
    std::ostringstream ss;
    ss << header("SiliconForge Design Report: " + name_);
    ss << "\n";

    for (auto& sec : sections_) {
        ss << "--- " << sec.title << " ---\n";
        ss << sec.content << "\n";
    }

    ss << separator();
    ss << "  Generated by SiliconForge v1.0\n";
    ss << separator();
    return ss.str();
}

} // namespace sf
